services:
  sqlserver-legacy:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqlserver-legacy
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  sqlserver-legacy-init:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqlserver-legcy-init
    depends_on:
      - sqlserver-legacy
    volumes:
      - ./db:/db
    user: root
    entrypoint: >
      /bin/bash -c "
      echo 'Waiting for SQL Server to boot up...' &&
      sleep 20 &&
      echo 'Running init.sql script...' &&
      /opt/mssql-tools18/bin/sqlcmd -S sqlserver-legacy -U sa -P '${DB_PASSWORD}' -C -i /db/init.sql &&
      echo 'Database initialization complete.'"

volumes:
  mssql-data:
